import {test,expect,type Page} from "@playwright/test";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {fileURLToPath} from "node:url";
const root=resolve(fileURLToPath(new URL("..",import.meta.url)));
async function move(page:Page,p:number){await page.evaluate(progress=>{const j=document.getElementById("journey");if(!j)throw Error("JOURNEY_MISSING");window.scrollTo({top:Math.max(0,j.offsetHeight-innerHeight)*progress,behavior:"instant"})},p);await expect.poll(()=>page.evaluate(()=>Number(document.body.dataset.storyProgress)),{timeout:8000}).toBeCloseTo(p,2)}
test("owner visuals stay byte-identical in source history",()=>{const receipt=JSON.parse(readFileSync(resolve(root,"owner-art-provenance.json"),"utf8"));for(const entry of receipt.assets){const bytes=readFileSync(resolve(root,"public",entry.asset.replace(/^\//,"")));expect(bytes.length).toBe(entry.bytes);expect(createHash("sha256").update(bytes).digest("hex")).toBe(entry.sha256)}});
test("one approved artist, two identity images, no numeric navigation and no five-world cards",async({page})=>{const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("/");await expect(page).toHaveTitle(/HAZEWAVE.*Indionesbala/);await expect(page.locator("body")).toHaveAttribute("data-experience","indionesbala-only");await expect(page.locator("img")).toHaveCount(2);await expect(page.locator("img[alt=HAZEWAVE]")).toHaveCount(1);await expect(page.locator("img[alt=Indionesbala]")).toHaveCount(1);expect(await page.locator(".chapter-nav,.planet,.artist-card,.hw-world,.world-switcher,[data-world-stop]").count()).toBe(0);expect(await page.locator("[aria-label^='Navegação entre']").count()).toBe(0);for(const forbidden of ["Barak Ozama","Baazü","Aquaverno","Hemorragia","Cinco mundos"])expect((await page.locator("body").innerText()).includes(forbidden)).toBe(false);expect(errors).toEqual([])});
test("scroll drives one continuous wave / MPC / Indionesbala reveal and reverses",async({page},info)=>{await page.goto("/");await expect.poll(()=>page.evaluate(()=>Boolean((window as unknown as {__HAZEWAVE_STORY?:{artistCount:number}}).__HAZEWAVE_STORY))).toBe(true);for(const [p,state] of [[0,"silence"],[.31,"interference"],[.55,"machine"],[.83,"handoff"],[.99,"artist"],[.55,"machine"],[0,"silence"]] as const){await move(page,p);await expect(page.locator("body")).toHaveAttribute("data-story-state",state);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1)}await move(page,.99);await expect(page.locator("#artist-entry")).toHaveAttribute("href","/artists/indionesbala/");await expect(page.locator("#artist-entry")).toHaveCSS("pointer-events","auto");await page.screenshot({path:info.outputPath("single-artist-reveal-"+info.project.name+".png")})});
test("sole artist destination works; other four routes are not emitted",async({page})=>{await page.goto("/artists/indionesbala/");await expect(page.locator("h1")).toHaveText("Indionesbala");await expect(page.locator("img")).toHaveCount(2);await expect(page.locator(".world-switcher,.planet,.artist-card")).toHaveCount(0);await expect.poll(()=>page.locator(".identity").evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);for(const slug of ["aquaverno","baazu","barak-ozama-beats","hemorragia-cosmica"]){const response=await page.goto("/artists/"+slug+"/");expect(response?.status()).toBe(404)}});
test("reduced motion and no JS preserve artist access",async({browser,page})=>{await page.emulateMedia({reducedMotion:"reduce"});await page.goto("/");await move(page,.92);await expect(page.locator("html")).toHaveAttribute("data-reduced-motion","true");const context=await browser.newContext({javaScriptEnabled:false});const blank=await context.newPage();await blank.goto("/");await expect(blank.locator("#arrival a")).toBeVisible();await context.close()});
